export default {
  FETCH_DRUGSTORES: "FETCH_DRUGSTORES",
  FETCH_DRUGSTORES_SUCCESS: "FETCH_DRUGSTORES_SUCCESS",
  FETCH_DRUGSTORES_ERROR: "FETCH_DRUGSTORES_ERROR",
  CLEAR_DRUGSTORES: "CLEAR_DRUGSTORES"
};
